### ISSUE TITLE
Should I git ignore the cache directory?

### ISSUE THREAD

**Issue by matepaiva** [htmlburger/wpemerge-theme#29]
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge Starter Theme: 0.15.0
  - WP Emerge (if not the default): 0.15.0
  - WordPress: 5.2.2
  - PHP: 7.2.19

## Expected behavior
I don't see any reason to do versioning on my cache files. Am I missing something?

## Actual behavior
theme/cache directory is not git ignored, so it is being commited. Is there any problem if I ignore it? Why it should not be like this by default? 

## Steps to reproduce (in case of a bug)

  1. yarn dev

**Comment by atanas-dev** [comment]
Hi @matepaiva 

`theme/cache` is not a default theme directory which is why it is not ignored. The path is an example for view extensions like blade and twig. There will be some directory changes coming to the theme soon which will most likely add a standard cache directory.
So you are correct - there is no need to version your cache directory - feel free to change the directory using the appropriate configuration option depending on the view extension you are using or just git ignore `theme/cache`.

**Comment by matepaiva** [comment]
Thanks! <3
