### ISSUE TITLE
.htaccess is blocking carbon fields assets

### ISSUE THREAD

**Issue by quasiperfect** [htmlburger/wpemerge-theme#37]
like the title said and also the comment from the actual file "# Disable access to any theme files outside of dist/."

**Comment by atanas-dev** [comment]
Hi @quasiperfect ,

Ultimately the .htaccess addition was a mistake on my part as it is overzealous and it's not the job of a theme to dictate how your webserver should behave which is why .htaccess will be removed in the next version.

I'd suggest you either remove it from your theme or add `vendor/htmlburger/carbon-fields/` or just `vendor/` to the pipe-separated list in the file like this:
```
# Disable access to any theme files outside of dist/.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule !^(dist/|theme/screenshot.png|theme/style.css|vendor/htmlburger/carbon-fields/) - [L,R=404]
</IfModule>
```

**Comment by quasiperfect** [comment]
thanks @atanas-angelov-dev for your work
