### ISSUE TITLE
Resolve image from scss file

### ISSUE THREAD

**Issue by anthonyvialleton** [htmlburger/wpemerge-theme#39]
## Version

  - WP Emerge Starter Theme: 0.15.1
  - WP Emerge (if not the default):
  - WordPress: 5.2.3
  - PHP: 7.3.8

## Expected behavior

Resolve image from any sass file with according hash

## Actual behavior & Steps to reproduce (in case of a bug)

I have a .svg file located here : `mytheme/resources/images/myfile.svg`

I import it into my `theme.js` using `import '@images/myfile.svg;` 

The file is well generated as follow : `mytheme/dist/images/myfile.12345.svg`

In my main index.scss file I have this error : `  Module not found: Error: Can't resolve '@dist/images/myfile.svg' in 'C:\xampp\htdocs\studiolv\wp-content\themes\mytheme\resources\styles\theme'` 
...when trying to use url css resolver like so : 
`cursor: url('~@dist/images/myfile.svg'), pointer;`

## Comments

I didn't change anything from webpack image's file-loader configuration.

**Comment by atanas-angelov-dev** [comment]
Hi @anthonyvialleton ,

`@dist` is not a valid alias - use `~@images/myfile.svg` in your .scss file instead. You should not need to reference anything in `dist/` in JS or SCSS - the references will be updated automatically (hence why there is no need for a `@dist` alias).

Also since the image is already referenced in SCSS, you don't need to import it in the main JS file - all images referenced in SCSS will be handled for you.

**Comment by atanas-dev** [comment]
Hi @anthonyvialleton ,

`@dist` is not what you need in this case - use `~@images/myfile.svg` in your .scss file instead. Under normal circumstances, you should not need to reference anything in `dist/` in JS or SCSS - the references will be updated automatically based on the source file.

Also since the image is already referenced in SCSS, you don't need to import it in the main JS file - all images referenced in SCSS will be handled for you.
